### ISSUE TITLE
Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by CantGetRight82** [pimalaya/comodoro#11]
Hi Soywood,

Already a fan of himalaya, I decided this one should also be good.
Unfortunately I'm having trouble on MacOS:

```
$ curl -sSL https://raw.githubusercontent.com/soywod/comodoro/master/install.sh | bash
Installing binaries...
tar: Error opening archive: Unrecognized archive format
```

**Comment by soywod** [comment]
It looks like the archive is either corrupted or not at the good format. Thanks for the feedback, I will check it out!

**Comment by soywod** [comment]
The projet as be rewrote in Rust, the archive should work better now using the command `curl -sSL https://pimalaya.org/comodoro/install.sh | bash`.
