### ISSUE TITLE
Not reading config.toml

### ISSUE THREAD

**Issue by dgrbrnl** [pimalaya/comodoro#14]
created file in ~/.config/comodoro/config.toml and it's not read. 
Changed to
work-time = 30

and comodoro is still starting with default value of 25

**Comment by soywod** [comment]
> created file in ~/.config/comodoro/config.toml and it's not read.

Mmmh I cannot reproduce the bug. Can you try in
`/tmp/comodoro/config.toml`?

**Comment by dgrbrnl** [comment]
> 

 I tried copying the file to /tmp/comodoro/config.toml and it's not taking the values either.

> created file in ~/.config/comodoro/config.toml and it's not read.
> Mmmh I cannot reproduce the bug. Can you try in `/tmp/comodoro/config.toml`?

**Comment by soywod** [comment]
I will try to add more logs to see what is happening.

**Comment by dgrbrnl** [comment]
> I will try to add more logs to see what is happening.

Thanks..let me know if you require to run a new test.

**Comment by soywod** [comment]
> I tried copying the file to /tmp/comodoro/config.toml and it's not
> taking the values either.

I will try to add more logs to see what is happening.

**Comment by soywod** [comment]
The project has been rewrote in Rust, the issue should not be there anymore. If you still have it let me know!
